name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            # Actualizar e instalar dependencias
            sudo apt-get -y update
            sudo apt-get install -y apache2 python3-venv python3-pip git

            # Navegar a la carpeta donde quieres desplegar el código
            cd ${{ secrets.TARGET_DIR }}

            # Asegúrate de que el repositorio se actualice
            git remote set-url origin git@github.com:alwxav98/AplicacionWeb-AWS.git
            git pull origin main

            # Crear un entorno virtual y activar
            python3 -m venv venv
            source venv/bin/activate

            # Instalar dependencias del archivo requirements.txt
            pip install -r requirements.txt

            # Reiniciar Apache
            sudo systemctl restart apache2
          EOF

      - name: Clean up
        run: |
          # Limpiar caché o realizar tareas de limpieza si es necesario
          echo "Deployment completed successfully!"
