name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: alwxav98/AplicacionWeb-AWS 

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
           
            sudo apt update -y
            sudo apt install python3-pip python3-dev apache2 libapache2-mod-wsgi-py3 git python3-venv -y

            cd /var/www/html/

            
            git pull origin main || git clone https://github.com/alwxav98/AplicacionWeb-AWS.git .

           
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

           
            source venv/bin/activate
            pip install -r requirements.txt

            
            sudo systemctl restart apache2
          EOF
