name: Deploy to EC2

# Definir el evento que activará el flujo de trabajo (cuando se haga un push al main)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
           
            sudo apt update -y
            sudo apt install python3-pip python3-dev apache2 libapache2-mod-wsgi-py3 git -y

           
            cd /var/www/html/

            
            git pull origin main || git clone https://github.com/tu-usuario/tu-repositorio.git .

            
            pip3 install -r /var/www/html/requirements.txt

            
            sudo systemctl restart apache2
          EOF
            sudo systemctl restart apache2
