name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.NOMBRE_DE_USUARIO }}@${{ secrets.HOST_DNS }} << 'EOF'
            cd ${{ secrets.TARGET_DIR }}

            # Cambiar la URL del repositorio a SSH si es necesario
            git remote set-url origin git@github.com:alwxav98/AplicacionWeb-AWS.git

            # Actualizar el código
            git pull origin main

            # Crear un entorno virtual y activar
            python3 -m venv venv
            source venv/bin/activate

            # Instalar dependencias
            pip install -r requirements.txt

            # Reiniciar Apache
            sudo systemctl restart apache2
          EOF
